fieldLayouts:
  dfeb10cd-510d-4ecf-a875-ba3d99015c96:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: homepage
hasUrls: true
name: Homepage
settings:
  path: '@webroot/images/uploads/homepage'
sortOrder: 1
type: craft\volumes\Local
url: '@web/images/'
