contentColumnType: string
fieldGroup: 377746dc-0283-4f24-ac57-9417416ceaee
handle: drawingImage
instructions: ''
name: 'Drawing Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:617e74de-ae87-4fe8-8f41-b24b566ce700'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a drawing'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:9da668f2-c1d0-4ac1-a085-88ff46ea8b0a'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:617e74de-ae87-4fe8-8f41-b24b566ce700'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
