contentColumnType: string
fieldGroup: 65b33c82-2b25-4363-8a5d-65f673795c6d
handle: featureImage
instructions: ''
name: 'Feature Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:bced7814-2d3f-48ed-b59d-81ece21d5e1f' # Decorative
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:bced7814-2d3f-48ed-b59d-81ece21d5e1f' # Decorative
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:bced7814-2d3f-48ed-b59d-81ece21d5e1f' # Decorative
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
