contentColumnType: text
fieldGroup: 377746dc-0283-4f24-ac57-9417416ceaee
handle: medium
instructions: ''
name: Medium
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
