enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  57c787ad-978a-4e6c-b80b-40ea855b4233: # Carl Avidano • Artist
    enabledByDefault: true
    hasUrls: true
    template: about/index
    uriFormat: about
type: single
