enableVersioning: true
handle: bio
name: Bio
propagationMethod: all
siteSettings:
  57c787ad-978a-4e6c-b80b-40ea855b4233:
    enabledByDefault: true
    hasUrls: true
    template: bio
    uriFormat: bio
type: single
