enableVersioning: false
handle: homeFeatured
name: 'Home Featured'
propagationMethod: all
siteSettings:
  57c787ad-978a-4e6c-b80b-40ea855b4233:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'home-features/{slug}'
type: channel
