enableVersioning: true
handle: reflections
name: Reflections
propagationMethod: all
siteSettings:
  57c787ad-978a-4e6c-b80b-40ea855b4233:
    enabledByDefault: true
    hasUrls: true
    template: reflections/_entry
    uriFormat: 'reflections/{slug}'
type: channel
