enableVersioning: true
handle: work
name: Work
propagationMethod: all
siteSettings:
  57c787ad-978a-4e6c-b80b-40ea855b4233:
    enabledByDefault: true
    hasUrls: true
    template: work/index
    uriFormat: 'work/{slug}'
structure:
  maxLevels: 2
  uid: 220e0909-1764-431c-952c-49af2842a7da
type: structure
